const STORAGE_KEY='ultimecia-war-room-v1';
const DEFAULT_STATE={
  config:{owner:'wagnerdante2-png',repo:'ultimecia-code',branch:'main',token:'',autoSync:false},
  meta:{lastSync:null,syncError:null},github:{repo:null,commits:[],branches:[],runs:[],tree:[]},
  checklist:[
    {id:'c1',area:'Fundação',title:'README / documentação base',description:'Documentação estrutural encontrada no repositório.',done:false,auto:true,pattern:'(^|/)README\\.md$|docs/',evidence:''},
    {id:'c2',area:'Qualidade',title:'Esteira de testes',description:'Arquivos de testes ou configuração de testes detectados.',done:false,auto:true,pattern:'(^|/)(test|tests|__tests__)/|\\.(test|spec)\\.|pytest|vitest|jest',evidence:''},
    {id:'c3',area:'Entrega',title:'Workflows GitHub Actions',description:'Há workflows versionados em .github/workflows.',done:false,auto:true,pattern:'^\\.github/workflows/.+\\.ya?ml$',evidence:''},
    {id:'c4',area:'Arquitetura',title:'Separação de engines/motores',description:'Estrutura de engines ou motores identificável no código.',done:false,auto:true,pattern:'engine|motor',evidence:''},
    {id:'c5',area:'Segurança',title:'Camada/protocolo de segurança',description:'Arquivos relacionados a safety, security, policy, guard ou permission.',done:false,auto:true,pattern:'security|safety|policy|guard|permission',evidence:''},
    {id:'c6',area:'Governança',title:'Decisões arquiteturais registradas',description:'Registro de ADR, decision record ou documentação equivalente.',done:false,auto:true,pattern:'(^|/)adr/|decision|architecture.*record',evidence:''},
    {id:'c7',area:'Resiliência',title:'Backup / persistência de conhecimento',description:'Verificação conceitual/manual do mecanismo de persistência e recuperação.',done:false,auto:false,evidence:''}
  ],
  roadmap:[
    {id:'r1',title:'Base operacional',description:'Fundação e arquitetura inicial',status:'done',wave:'Fundação'},
    {id:'r2',title:'Inteligência de voz',description:'Evolução atual do branch de voice intelligence',status:'progress',wave:'F8'},
    {id:'r3',title:'War Room',description:'Central de observação e governança',status:'progress',wave:'Governança'},
    {id:'r4',title:'Protocolos avançados de segurança',description:'Estudo e implementação futura',status:'planned',wave:'Futuro'}
  ],
  studies:[
    {id:'s1',title:'Cofre de conhecimento',category:'Arquitetura',status:'study',notes:'Persistência segura do conhecimento adquirido e capacidade de restauração/replicação.'},
    {id:'s2',title:'Kill switch e contenção',category:'Segurança',status:'study',notes:'Protocolos de desabilitação, limitação de escopo e resposta a comportamento fora do esperado.'}
  ],
  decisions:[],debt:[]
};

const NAV=[
  ['CENTRAL',[['dashboard','⌂','Visão Geral'],['checklist','✓','Checklist Mestre'],['roadmap','◫','Roadmap / Ondas']]],
  ['CONHECIMENTO',[['studies','◇','Estudos Futuros'],['decisions','◆','Decisões'],['debt','△','Dívida Técnica']]],
  ['CONTROLE',[['github','⌁','Monitor GitHub'],['backup','⇩','Backup'],['config','⚙','Configuração']]]
];
const titles={dashboard:['CENTRAL DE COMANDO','Visão Geral'],checklist:['REALIDADE × PLANO','Checklist Mestre'],roadmap:['PLANO','Roadmap / Ondas'],studies:['VISÃO','Estudos Futuros'],decisions:['GOVERNANÇA','Decisões Arquiteturais'],debt:['QUALIDADE','Dívida Técnica'],github:['REALIDADE','Monitor GitHub'],backup:['CONTINUIDADE','Backup da War Room'],config:['INTEGRAÇÃO','Configuração']};
let state=loadState(),currentView='dashboard';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return s?mergeDefaults(s):structuredClone(DEFAULT_STATE)}catch{return structuredClone(DEFAULT_STATE)}}
function mergeDefaults(s){return {...structuredClone(DEFAULT_STATE),...s,config:{...DEFAULT_STATE.config,...(s.config||{})},meta:{...DEFAULT_STATE.meta,...(s.meta||{})},github:{...DEFAULT_STATE.github,...(s.github||{})}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateConnection()}
function uid(prefix='i'){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d)?'—':d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function statusBadge(s){const map={done:['green','Concluído'],progress:['yellow','Em andamento'],planned:['blue','Planejado'],blocked:['red','Bloqueado'],study:['purple','Em estudo'],accepted:['green','Aceita'],open:['yellow','Aberta'],critical:['red','Crítica'],medium:['yellow','Média'],low:['blue','Baixa'],success:['green','Sucesso'],failure:['red','Falha'],cancelled:['yellow','Cancelado'],queued:['blue','Fila'],in_progress:['yellow','Executando']};const x=map[s]||['',''+s];return `<span class="badge ${x[0]}">${x[1]}</span>`}
function renderNav(){let html='';for(const [group,items] of NAV){html+=`<div class="nav-group-title">${group}</div>`;for(const [id,icon,label] of items)html+=`<button class="nav-btn ${id===currentView?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span>${label}</button>`}$('#nav').innerHTML=html;document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>navigate(b.dataset.view))}
function navigate(v){currentView=v;const t=titles[v];$('#pageEyebrow').textContent=t[0];$('#pageTitle').textContent=t[1];renderNav();render()}
function updateConnection(){const dot=$('#connectionDot'),label=$('#connectionLabel');$('#lastSync').textContent=state.meta.lastSync?`Sync ${fmtDate(state.meta.lastSync)}`:'Nunca sincronizado';dot.className='connection-dot';if(state.meta.syncError){dot.classList.add('error');label.textContent='Erro de conexão'}else if(state.meta.lastSync){dot.classList.add('ok');label.textContent='Sincronizado'}else label.textContent='Não sincronizado'}
function progressStats(){const total=state.checklist.length,done=state.checklist.filter(x=>x.done).length;return {total,done,pct:total?Math.round(done/total*100):0}}
function runStats(){const runs=state.github.runs||[];return {ok:runs.filter(r=>r.conclusion==='success').length,fail:runs.filter(r=>r.conclusion==='failure').length,total:runs.length}}
function render(){updateConnection();const fn={dashboard:renderDashboard,checklist:renderChecklist,roadmap:renderRoadmap,studies:()=>renderCollection('studies'),decisions:()=>renderCollection('decisions'),debt:()=>renderCollection('debt'),github:renderGithub,backup:renderBackup,config:renderConfig}[currentView];fn()}
function metric(label,value,sub=''){return `<div class="metric"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div></div>`}
function renderDashboard(){const p=progressStats(),rs=runStats(),repo=state.github.repo,head=state.github.commits[0];$('#view').innerHTML=`
<div class="hero"><div class="eyebrow">ULTIMECIA PROJECT INTELLIGENCE</div><h2>Uma única visão para saber onde o projeto realmente está.</h2><p>A War Room separa fatos detectados no GitHub, compromissos do plano e ideias em estudo. Nenhuma alteração é feita no repositório monitorado.</p><div class="truth-columns"><div class="truth"><span class="badge green">REALIDADE</span><p>Arquivos, commits, branches e Actions encontrados no GitHub.</p></div><div class="truth"><span class="badge blue">PLANO</span><p>Checklist e roadmap controlados pela War Room.</p></div><div class="truth"><span class="badge purple">VISÃO</span><p>Estudos e hipóteses ainda não incorporados ao código.</p></div></div></div>
<div class="grid metrics">${metric('Checklist',p.pct+'%',`${p.done} de ${p.total} itens`)}${metric('Commits lidos',state.github.commits.length,head?`HEAD ${head.sha?.slice(0,7)||''}`:'Sem sincronização')}${metric('Branches',state.github.branches.length,repo?.default_branch?`default: ${repo.default_branch}`:'GitHub')}${metric('Actions',rs.total,rs.total?`${rs.ok} sucesso · ${rs.fail} falha`:'Sem dados')}</div>
<div class="grid two"><div class="card"><div class="card-header"><div><div class="card-title">Progresso do checklist</div><div class="card-subtitle">Itens manuais + evidências automáticas</div></div><strong>${p.pct}%</strong></div><div class="progress"><span style="width:${p.pct}%"></span></div><div style="margin-top:16px">${state.checklist.slice(0,6).map(x=>`<div class="check-item"><div class="check-box ${x.done?'done':''}">${x.done?'✓':''}</div><div class="check-main"><strong>${esc(x.title)}</strong><p>${esc(x.area)}${x.evidence?` · <span class="code">${esc(x.evidence)}</span>`:''}</p></div>${x.auto?'<span class="badge purple">auto</span>':'<span class="badge">manual</span>'}</div>`).join('')}</div></div>
<div class="card"><div class="card-header"><div><div class="card-title">Atividade recente</div><div class="card-subtitle">Últimos commits sincronizados</div></div></div>${state.github.commits.length?state.github.commits.slice(0,7).map(c=>`<div class="commit"><div class="sha">${esc(c.sha.slice(0,7))}</div><div><strong>${esc((c.commit?.message||'').split('\n')[0])}</strong><span>${esc(c.commit?.author?.name||'')} · ${fmtDate(c.commit?.author?.date)}</span></div></div>`).join(''):'<div class="empty">Sincronize o GitHub para preencher esta área.</div>'}</div></div>`}
function renderChecklist(){const p=progressStats();$('#view').innerHTML=`<div class="split-header"><div><h2 class="section-title">${p.done}/${p.total} itens concluídos</h2><div class="section-desc">Itens AUTO são recalculados a cada sincronização pelo caminho dos arquivos.</div></div><button class="btn primary" id="addChecklist">+ Novo item</button></div><div class="card"><div class="card-header"><div class="progress" style="flex:1"><span style="width:${p.pct}%"></span></div><strong>${p.pct}%</strong></div><div id="checks">${state.checklist.map(x=>`<div class="check-item"><button class="check-box ${x.done?'done':''}" data-toggle="${x.id}" ${x.auto?'title="Atualizado automaticamente"':''}>${x.done?'✓':''}</button><div class="check-main"><div class="status-row"><strong>${esc(x.title)}</strong>${x.auto?'<span class="badge purple">auto</span>':'<span class="badge">manual</span>'}</div><p>${esc(x.area)} · ${esc(x.description)}</p>${x.evidence?`<p class="evidence">evidência: ${esc(x.evidence)}</p>`:''}</div><div class="actions"><button class="icon-btn" data-edit="${x.id}">✎</button><button class="icon-btn" data-del="${x.id}">×</button></div></div>`).join('')}</div></div>`;$('#addChecklist').onclick=()=>openEditor('checklist');document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const x=state.checklist.find(i=>i.id===b.dataset.toggle);if(x&&!x.auto){x.done=!x.done;save();render()}});wireEditDelete('checklist')}
function renderRoadmap(){const lanes=[['planned','Planejado'],['progress','Em andamento'],['blocked','Bloqueado'],['done','Concluído']];$('#view').innerHTML=`<div class="split-header"><div><h2 class="section-title">Ondas e frentes de evolução</h2><div class="section-desc">Visão simples do que vem depois, do que está ativo e do que já foi encerrado.</div></div><button class="btn primary" id="addRoad">+ Nova frente</button></div><div class="lane-grid">${lanes.map(([s,label])=>`<div class="lane"><h3>${label} · ${state.roadmap.filter(x=>x.status===s).length}</h3>${state.roadmap.filter(x=>x.status===s).map(x=>`<div class="road-card"><span class="badge ${s==='done'?'green':s==='blocked'?'red':s==='progress'?'yellow':'blue'}">${esc(x.wave||'Roadmap')}</span><strong style="margin-top:8px">${esc(x.title)}</strong><p>${esc(x.description)}</p><div class="actions"><button class="icon-btn" data-edit="${x.id}">✎</button><button class="icon-btn" data-del="${x.id}">×</button></div></div>`).join('')}</div>`).join('')}</div>`;$('#addRoad').onclick=()=>openEditor('roadmap');wireEditDelete('roadmap')}
const collectionMeta={studies:{title:'Estudos',desc:'Ideias e hipóteses que ainda não fazem parte da arquitetura oficial.',button:'Novo estudo',cols:['Categoria','Status']},decisions:{title:'Decisões',desc:'Registre o que foi decidido e por quê. Isto reduz rediscussão e perda de contexto.',button:'Nova decisão',cols:['Data','Status']},debt:{title:'Dívida Técnica',desc:'Pendências conhecidas que funcionam hoje, mas merecem revisão.',button:'Nova dívida',cols:['Área','Severidade']}};
function renderCollection(type){const m=collectionMeta[type],items=state[type];$('#view').innerHTML=`<div class="split-header"><div><h2 class="section-title">${m.title}</h2><div class="section-desc">${m.desc}</div></div><button class="btn primary" id="addCol">+ ${m.button}</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Título</th><th>${m.cols[0]}</th><th>${m.cols[1]}</th><th></th></tr></thead><tbody>${items.length?items.map(x=>rowFor(type,x)).join(''):`<tr><td colspan="4"><div class="empty">Nenhum registro ainda.</div></td></tr>`}</tbody></table></div></div>`;$('#addCol').onclick=()=>openEditor(type);wireEditDelete(type)}
function rowFor(type,x){if(type==='studies')return `<tr><td class="title-cell"><strong>${esc(x.title)}</strong><span>${esc(x.notes)}</span></td><td>${esc(x.category)}</td><td>${statusBadge(x.status)}</td>${act(x.id)}</tr>`;if(type==='decisions')return `<tr><td class="title-cell"><strong>${esc(x.title)}</strong><span>${esc(x.notes)}</span></td><td>${esc(x.date||'—')}</td><td>${statusBadge(x.status)}</td>${act(x.id)}</tr>`;return `<tr><td class="title-cell"><strong>${esc(x.title)}</strong><span>${esc(x.notes)}</span></td><td>${esc(x.area)}</td><td>${statusBadge(x.severity)}</td>${act(x.id)}</tr>`}
function act(id){return `<td><div class="actions"><button class="icon-btn" data-edit="${id}">✎</button><button class="icon-btn" data-del="${id}">×</button></div></td>`}
function wireEditDelete(type){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(type,b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Excluir este registro?')){state[type]=state[type].filter(x=>x.id!==b.dataset.del);save();render()}})}
function renderGithub(){const repo=state.github.repo,rs=runStats();$('#view').innerHTML=`<div class="grid metrics">${metric('Repositório',repo?.name||'—',repo?.private?'privado':'')}${metric('Branch padrão',repo?.default_branch||'—',`${state.github.branches.length} branches lidas`)}${metric('Arquivos',state.github.tree.length,'árvore recursiva')}${metric('Actions',rs.total,`${rs.ok} sucesso · ${rs.fail} falha`)}</div><div class="grid two"><div class="card"><div class="card-header"><div><div class="card-title">Commits recentes</div><div class="card-subtitle">${esc(state.config.owner+'/'+state.config.repo)}</div></div></div>${state.github.commits.length?state.github.commits.map(c=>`<div class="commit"><div class="sha">${esc(c.sha.slice(0,7))}</div><div><strong>${esc((c.commit?.message||'').split('\n')[0])}</strong><span>${esc(c.commit?.author?.name||'')} · ${fmtDate(c.commit?.author?.date)}</span></div></div>`).join(''):'<div class="empty">Sem dados.</div>'}</div><div><div class="card"><div class="card-header"><div class="card-title">Branches</div></div><div class="branch-list">${state.github.branches.length?state.github.branches.map(b=>`<span class="badge ${b.name===state.config.branch?'purple':''}">${esc(b.name)}</span>`).join(''):'<span class="muted small">Sem dados.</span>'}</div></div><div class="card"><div class="card-header"><div class="card-title">Workflow runs</div></div>${state.github.runs.length?state.github.runs.map(r=>`<div class="check-item"><div class="check-main"><strong>${esc(r.name||r.display_title||'Workflow')}</strong><p>${esc(r.head_branch||'')} · ${fmtDate(r.created_at)}</p></div>${statusBadge(r.conclusion||r.status)}</div>`).join(''):'<div class="empty">Sem dados de Actions.</div>'}</div></div></div>`}
function renderBackup(){$('#view').innerHTML=`<div class="grid two"><div class="card"><div class="card-header"><div><div class="card-title">Exportar estado completo</div><div class="card-subtitle">Gera um JSON com checklist, estudos, decisões, roadmap e configuração.</div></div></div><p class="notice">O backup inclui a configuração local. Se houver token GitHub salvo, ele também será incluído. Guarde o arquivo com segurança.</p><button class="btn primary" id="exportBtn">⇩ Exportar JSON</button></div><div class="card"><div class="card-header"><div><div class="card-title">Importar backup</div><div class="card-subtitle">Substitui o estado local atual.</div></div></div><p class="notice">Use apenas um arquivo exportado por esta War Room. A importação pede confirmação antes de substituir os dados atuais.</p><button class="btn secondary" id="importBtn">⇧ Importar JSON</button></div></div>`;$('#exportBtn').onclick=exportBackup;$('#importBtn').onclick=()=>$('#importFile').click()}
function renderConfig(){$('#view').innerHTML=`<div class="card"><div class="card-header"><div><div class="card-title">Repositório monitorado</div><div class="card-subtitle">A War Room somente lê informações pela API do GitHub.</div></div></div><div class="config-grid"><div class="field"><label>Owner</label><input id="cfgOwner" value="${esc(state.config.owner)}"></div><div class="field"><label>Repositório</label><input id="cfgRepo" value="${esc(state.config.repo)}"></div><div class="field"><label>Branch de referência</label><input id="cfgBranch" value="${esc(state.config.branch)}"></div><div class="field"><label>Personal Access Token</label><input id="cfgToken" type="password" value="${esc(state.config.token)}" placeholder="github_pat_..."></div></div><div class="notice">Como <strong>ultimecia-code</strong> é privado, a sincronização no navegador precisa de um token. Prefira um fine-grained PAT restrito a esse único repositório e somente leitura. O token fica no localStorage desta máquina.</div><div style="margin-top:14px;display:flex;gap:8px"><button class="btn primary" id="saveConfig">Salvar configuração</button><button class="btn secondary" id="saveSync">Salvar e sincronizar</button></div></div>`;const doSave=()=>{state.config.owner=$('#cfgOwner').value.trim();state.config.repo=$('#cfgRepo').value.trim();state.config.branch=$('#cfgBranch').value.trim()||'main';state.config.token=$('#cfgToken').value.trim();save()};$('#saveConfig').onclick=()=>{doSave();alert('Configuração salva localmente.')};$('#saveSync').onclick=async()=>{doSave();await syncGithub()}}
async function gh(path){const h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(state.config.token)h.Authorization=`Bearer ${state.config.token}`;const r=await fetch(`https://api.github.com${path}`,{headers:h});if(!r.ok){let msg=`GitHub ${r.status}`;try{const j=await r.json();msg+=': '+j.message}catch{}throw new Error(msg)}return r.json()}
async function syncGithub(){const btn=$('#syncBtn');btn.disabled=true;btn.textContent='Sincronizando...';state.meta.syncError=null;try{const {owner,repo,branch}=state.config;if(!owner||!repo)throw new Error('Configure owner e repositório.');const base=`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`;const [repoData,commits,branches,runs,tree]=await Promise.all([gh(base),gh(`${base}/commits?sha=${encodeURIComponent(branch)}&per_page=15`),gh(`${base}/branches?per_page=100`),gh(`${base}/actions/runs?per_page=12`),gh(`${base}/git/trees/${encodeURIComponent(branch)}?recursive=1`)]);state.github.repo=repoData;state.github.commits=commits||[];state.github.branches=branches||[];state.github.runs=runs.workflow_runs||[];state.github.tree=(tree.tree||[]).filter(x=>x.type==='blob');applyAutoChecklist();state.meta.lastSync=new Date().toISOString();save();render();alert('GitHub sincronizado e checklist automático recalculado.')}catch(e){state.meta.syncError=e.message;save();render();alert(`Não foi possível sincronizar: ${e.message}\n\nSe o repositório for privado, configure um PAT de leitura na aba Configuração.`)}finally{btn.disabled=false;btn.textContent='↻ Sincronizar GitHub'}}
function applyAutoChecklist(){const paths=state.github.tree.map(x=>x.path);for(const item of state.checklist.filter(x=>x.auto&&x.pattern)){try{const re=new RegExp(item.pattern,'i'),matches=paths.filter(p=>re.test(p));item.done=matches.length>0;item.evidence=matches.slice(0,3).join(' · ')}catch{item.done=false;item.evidence='padrão inválido'}}}
function fieldsFor(type,x={}){if(type==='checklist')return [['title','Título','text',x.title],['area','Área','text',x.area],['description','Descrição','textarea',x.description],['auto','Modo','select',x.auto?'auto':'manual',[['manual','Manual'],['auto','Automático']]],['pattern','Regex de evidência (para AUTO)','text',x.pattern]];if(type==='roadmap')return [['title','Título','text',x.title],['wave','Onda / Frente','text',x.wave],['description','Descrição','textarea',x.description],['status','Status','select',x.status||'planned',[['planned','Planejado'],['progress','Em andamento'],['blocked','Bloqueado'],['done','Concluído']]]];if(type==='studies')return [['title','Título','text',x.title],['category','Categoria','text',x.category],['status','Status','select',x.status||'study',[['study','Em estudo'],['planned','Planejado'],['accepted','Aceita']]],['notes','Notas','textarea',x.notes]];if(type==='decisions')return [['title','Decisão','text',x.title],['date','Data','date',x.date||new Date().toISOString().slice(0,10)],['status','Status','select',x.status||'accepted',[['accepted','Aceita'],['open','Aberta']]],['notes','Motivo / contexto','textarea',x.notes]];return [['title','Dívida','text',x.title],['area','Área','text',x.area],['severity','Severidade','select',x.severity||'medium',[['critical','Crítica'],['medium','Média'],['low','Baixa']]],['notes','Notas','textarea',x.notes]]}
function openEditor(type,id){const arr=state[type],existing=id?arr.find(x=>x.id===id):null,fields=fieldsFor(type,existing||{});$('#modalEyebrow').textContent=type.toUpperCase();$('#modalTitle').textContent=existing?'Editar registro':'Novo registro';$('#modalFields').innerHTML=fields.map(([name,label,kind,val,opts])=>`<div class="field"><label>${label}</label>${kind==='textarea'?`<textarea name="${name}">${esc(val||'')}</textarea>`:kind==='select'?`<select name="${name}">${opts.map(o=>`<option value="${o[0]}" ${String(val)===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select>`:`<input name="${name}" type="${kind}" value="${esc(val||'')}">`}</div>`).join('');const modal=$('#modal');modal.showModal();$('#modalSave').onclick=e=>{e.preventDefault();const fd=new FormData($('#modalForm')),obj=existing?{...existing}:{id:uid(type[0])};for(const [name,,,] of fields){let v=fd.get(name);if(type==='checklist'&&name==='auto')v=v==='auto';obj[name]=v}if(!obj.title?.trim()){alert('Informe um título.');return}if(existing)Object.assign(existing,obj);else arr.unshift(obj);save();modal.close();render()}}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ultimecia-war-room-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!confirm('Importar este backup e substituir os dados locais atuais?'))return;state=mergeDefaults(data);save();render();alert('Backup importado.')}catch{alert('Arquivo JSON inválido.')}finally{e.target.value=''}};
$('#syncBtn').onclick=syncGithub;
renderNav();render();
